
- hosts: tag_Name_soulswapserver
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /mnt/f/proyectos/zorzano/claves/mortadelo.pem
    ansible_python_interpreter: /usr/bin/python3

  tasks:

          #    - name: install python 2
          #raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
 
    - name: Check the monster is alive and well
      ping: 

    - name: ensure nginx is at the latest version
      apt: update_cache=yes name=nginx state=latest
      become: yes

    - name: start nginx
      service:
         name: nginx
         state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
         src: /home/zorzano/SoulSwap/webserver/config/soulswap.cfg
         dest: /etc/nginx/sites-available/soulswap.cfg
      become: yes
    - name: create symlink
      file:
         src: /etc/nginx/sites-available/soulswap.cfg
         dest: /etc/nginx/sites-enabled/default
         state: link
      become: yes
    - name: copy the content of the web site
      copy:
         src: /home/zorzano/SoulSwap/webserver/static-site
         dest: /home/ubuntu/
    - name: restart nginx
      service:
         name: nginx
         state: restarted
      become: yes


      #    - name: Terminate instances that were previously launched
      #     ec2:
      #  state: 'absent'
      #  instance_ids: '{{ ec2.instance_ids }}'
      #  region: eu-west-1
