
- hosts: tag_Name_soulswapserver
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /mnt/f/proyectos/zorzano/claves/mortadelo.pem
    ansible_python_interpreter: /usr/bin/python3

  tasks:

          #    - name: install python 2
          #raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Check the monster is alive and well
      ping:

    - name: ensure nginx is at the latest version
      apt: update_cache=yes name=nginx state=latest
      become: yes

    - name: start nginx
      service:
         name: nginx
         state: started
      become: yes

    - name: deploy pip
      apt: update_cache=yes name=python-pip state=latest
      become: yes

    - name: deploy virtualenv
      apt: update_cache=yes name=python-virtualenv state=latest
      become: yes


    - name: deploy gunicorn
      apt: update_cache=yes name=gunicorn state=latest
      become: yes

    - name: deploy flask
      pip name=flask

    - name: simple gunicorn run example
      gunicorn:
         app: 'app'
         chdir: '/home/ubuntu/SoulSwap/webserver/dynamic-site'

      #    - name: Terminate instances that were previously launched
      #     ec2:
      #  state: 'absent'
      #  instance_ids: '{{ ec2.instance_ids }}'
      #  region: eu-west-1
