- hosts: dynamic_machines
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /mnt/f/proyectos/zorzano/claves/mortadelo.pem
    ansible_python_interpreter: /usr/bin/python3

  tasks:  

  - name: Ping
    ping:  


